vim9script

# BASIC
syntax on
filetype plugin indent on

# Clipboard
set clipboard=unnamedplus

# Colorscheme
hi Pmenu ctermfg=231 ctermbg=238
hi PmenuSel ctermfg=16 ctermbg=44

# Completion
set path+=.,,components/**,pages/**
set wildmenu
set wildmode=longest:full,full
set wildoptions=pum
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
set wildignorecase

# Tab
set shiftwidth=4
set tabstop=4
set expandtab
set smarttab

# List
#set list
#set listchars=tab:▶\ ,trail:⋅

# Searching
set incsearch
set ignorecase
set smartcase
set showmatch
set hlsearch

# Split Window
set splitright
set splitbelow

# Numbering
set number
set relativenumber

set colorcolumn=81
set cursorline
set nowrap

set shell=/usr/bin/zsh
tnoremap <ESC> <C-W>:q!<CR>

# Open Help Vertically
cabbrev h vert h

# Open Split Buffer Vertically
cabbrev vsb vert sb

#set hidden

# Scrolling
set scrolloff=5

# BASIC END

# MAPPINGS
# Clipboard
nnoremap Y "+y

# nohighlight
nnoremap <leader><leader> :nohl<CR>

# Split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

# MAPPINGS END
# VIMSCRIPT

au Filetype netrw :vert resize 20

augroup ReduceNoise
    autocmd!
    # Automatically resize active split to 80 width
    autocmd WinEnter * :call ResizeSplits()
augroup END

def ResizeSplits()
    if &ft != 'netrw'
        set winwidth=80
        wincmd =
    endif
enddef


# Mouse
set mouse=a
g:is_mouse_enabled = 0
noremap <silent> <Leader>m :call ToggleMouse()<CR>
def g:ToggleMouse()
    if g:is_mouse_enabled == 1
        echo "Mouse OFF"
        set mouse=
        g:is_mouse_enabled = 0
    else
        echo "Mouse ON"
        set mouse=a
        g:is_mouse_enabled = 1
    endif
enddef

# PLUGIN CONFIG
# netrw
g:netrw_winsize = 20
g:netrw_banner = 0
g:netrw_liststyle = 3
g:netrw_keepdir = 0
cabbrev l. Lexplore %:p:h

# airline
g:airline_powerline_fonts = 1
 
# PLUGIN END

